name: _
publish_to: none
environment:
  sdk: ^3.10.4
workspace:
  - packages/pjatk_core
  - packages/app
  - packages/server
  - packages/flutter_adaptive_scaffold
  
dev_dependencies:
  build_runner: ^2.10.5
