name: pjatka
description: "PJATK App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  talker: ^5.1.9
  syncfusion_flutter_calendar: ^32.1.22
  freezed_annotation: ^3.1.0
  html: ^0.15.4
  timezone: ^0.10.0
  intl: any
  json_annotation: ^4.9.0
  sizer: ^3.1.3
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  talker_dio_logger: ^5.1.9
  semaphore: ^0.2.1
  flutter_hooks: ^0.21.3+1
  canonical_adaptive_scaffold: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.0+1
  drift_dev: ^2.30.0

flutter:
  uses-material-design: true